version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
      - "5050:5050"
    depends_on:
      - db
      - keycloak

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://kafka:29092, EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092, EXTERNAL://localhost:9092

      # if backend not in docker container:
      #      KAFKA_LISTENERS: INTERNAL://localhost:29092, EXTERNAL://localhost:9092
      #      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:29092,EXTERNAL://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: reporting
    ports:
      - "8085:27017"
    volumes:
      - ./conf/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.stats().ok' | mongo mongo:27017/reporting --quiet
      start_period: 10s

  keycloak:
#    image: jboss/keycloak:13.0.0
    image: wizzn/keycloak:12
    ports:
      - "8090:8090"
    volumes:
      - ./conf:/opt/jboss/keycloak/imports
      - ./keycloak-db:/opt/jboss/keycloak/standalone/data
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.strategy=IGNORE_EXISTING -Djboss.socket.binding.port-offset=10"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    healthcheck:
      test: "curl -f http://localhost:8090/auth || exit 1"
      start_period: 20s

  pingponger:
    build: KafkaPingPonger/
    ports:
      - "8888:8888"
    depends_on:
      - kafka
      - zookeeper


#"-Djboss.socket.binding.port-offset=10"