package com.sciamus.contractanalyzer.domain.checks.reports;


import lombok.Getter;

import java.time.LocalDateTime;


@Getter
public class Report {


    private String id;
    private final ReportResults result;
    private String reportBody;
    private final String nameOfCheck;
    private LocalDateTime timestamp;
    private final String userName;


    public Report(String id, ReportResults result, String reportBody, LocalDateTime timestamp, String nameOfCheck, String userName) {
        this.id = id;
        this.result = result;
        this.reportBody = reportBody;
        this.timestamp = timestamp;
        this.nameOfCheck = nameOfCheck;
        this.userName = userName;
    }


    public Report addAutogenerated() {
        this.reportBody  = reportBody + " [this report was autogenerated]";
        return this;
    }

    @Override
    public String toString() {
        return "CheckReport{" +
                "id='" + id + '\'' +
                ", result=" + result +
                ", reportBody='" + reportBody + '\'' +
                ", nameOfCheck='" + nameOfCheck + '\'' +
                ", timestamp=" + timestamp + '\'' +
                ", userName='" + userName +
                '}';
    }
}



