server:
  error:
    whitelabel:
      enabled: true
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false

spring:
  data:
    mongodb:
#      uri: "mongodb+srv://m001-student:Orixa1911@sandbox.opih2.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
      uri: "mongodb://root:root@localhost:8085/"
      database: reporting


keycloak:
  auth-server-url: http://localhost:8083/auth
  realm: contractAnalyzer
  resource: contract-analyzer-backend
  public-client: true
  ssl-required: external
#  use-resource-role-mappings: true
  confidential-port: 0
