package com.sciamus.contractanalyzer.domain.suites;

import com.sciamus.contractanalyzer.application.ContractChecksService;
import com.sciamus.contractanalyzer.domain.checks.CheckRepository;
import com.sciamus.contractanalyzer.domain.reporting.checks.CheckReport;
import com.sciamus.contractanalyzer.domain.reporting.suites.SuiteReport;
import com.sciamus.contractanalyzer.domain.reporting.suites.SuiteReportMapper;
import io.vavr.collection.List;
import io.vavr.control.Try;
import org.springframework.stereotype.Component;

import java.net.URL;

@Component
public class BasicSuite extends CheckSuite {

    private final String NAME = "Basic Suite";

    private final String DESCRIPTION = "Runs 3 first checks of the system";

    ContractChecksService contractChecksService;
    CheckRepository checkRepository;
    SuiteReportMapper mapper;


    public BasicSuite(ContractChecksService contractChecksService,
                      SuiteReportMapper mapper,
                      CheckRepository checkRepository) {
        super();
        this.contractChecksService = contractChecksService;
        this.mapper = mapper;
        this.checkRepository = checkRepository;
    }


    public String getName() {
        return NAME;
    }

    @Override
    public SuiteReport run(URL url) {


        List<CheckReport> checkReports = List.ofAll(checkRepository.getAllChecks().stream())
                .take(3)
                .peek(System.out::println)
                .map(s -> Try.of(()-> contractChecksService
                        .runAndGetSavedAutogeneratedReportWithId(s, urlToStringTransform(url)))
                        .getOrElseThrow(throwable -> new RuntimeException()))
                .collect(List.collector());


        SuiteReport suiteReport = new SuiteReport(checkReports.toJavaList());
        return suiteReport;

    }
    private String urlToStringTransform(URL url)  {
        return String.valueOf(url);
    }

}