package com.sciamus.contractanalyzer.reporting;


import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.PersistenceConstructor;
import org.springframework.data.annotation.Transient;
import org.springframework.data.annotation.TypeAlias;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.util.Date;

@Document(collection = "contractanalyzer")
@TypeAlias("test_report")

public class TestReport {



    //TODO: review: kiedy to pole się tworzy, nie jestem pewien tego rozwiązania

    @Id
    private String id;
    @Field("result")
    private final ReportResults result;
    @Field("content")
    private String reportBody;
    @Field("name")
    private final String nameOfCheck;
    @Field("timestamp")
            //review: is it precise enough?
    Date timestamp;

    @PersistenceConstructor
    public TestReport(String id, ReportResults result, String reportBody, Date timestamp, String nameOfCheck) {
        this.id = id;
        this.result = result;
        this.reportBody = reportBody;
        this.timestamp = timestamp;
        this.nameOfCheck = nameOfCheck;

    }

//     TO REVIEW:
//    public TestReport(ReportResults result, String reportBody, String nameOfCheck) {
//
//        this.result = result;
//        this.reportBody = reportBody;
//        this.nameOfCheck = nameOfCheck;
//       }



    // nie jestem pewien tego rozwiązania
    void addId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public ReportResults getResult() {
        return this.result;
    }


    //TODO: czy to nie jest przypał:
    public TestReport addAutogenerated() {
        this.reportBody  = reportBody + " [this report was autogenerated]";
        return this;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public String getReportBody() {
        return reportBody;
    }

    public String getNameOfCheck() {
        return nameOfCheck;
    }

    }



