package com.sciamus.contractanalyzer.domain.checks.suites;

import com.sciamus.contractanalyzer.application.CheckReportDTO;
import com.sciamus.contractanalyzer.application.ContractChecksFacade;
import com.sciamus.contractanalyzer.application.mapper.CheckReportMapper;
import com.sciamus.contractanalyzer.domain.checks.rest.CheckRepository;
import com.sciamus.contractanalyzer.domain.checks.reports.CheckReport;
import com.sciamus.contractanalyzer.domain.checks.suites.reports.SuiteReport;
import io.vavr.collection.List;
import io.vavr.control.Try;
import org.springframework.beans.factory.annotation.Autowired;

import java.net.URL;

public class BasicSuite extends CheckSuite {

    private final String NAME = "Basic Suite";

    private final String DESCRIPTION = "Runs 3 first checks of the system";

    private final ContractChecksFacade contractChecksFacade;

    private final CheckRepository checkRepository;

    private final CheckReportMapper checkReportMapper;

    @Autowired
    public BasicSuite(ContractChecksFacade contractChecksFacade, CheckRepository checkRepository, CheckReportMapper checkReportMapper) {
        super();
        this.contractChecksFacade = contractChecksFacade;
        this.checkRepository = checkRepository;
        this.checkReportMapper = checkReportMapper;
    }

    public String getName() {
        return NAME;
    }

    @Override
    public SuiteReport run(URL url) {


        List<CheckReportDTO> checkReportDTOS = List.ofAll(checkRepository.getAllChecks().stream())
                .take(3)
                .peek(System.out::println)
                .map(s -> Try.of(()-> contractChecksFacade
                        .runAndGetSavedAutogeneratedReportWithId(s, urlToStringTransform(url)))
                        .getOrElseThrow(throwable -> new RuntimeException(throwable)))
                .collect(List.collector());


        List<CheckReport> checkReports = checkReportDTOS
                .toStream()
                .map(checkReportDTO -> checkReportMapper.mapFromDTO(checkReportDTO))
                .collect(List.collector());

        SuiteReport suiteReport = new SuiteReport(checkReports.toJavaList());
        return suiteReport;

    }
    private String urlToStringTransform(URL url)  {
        return String.valueOf(url);
    }

}