package com.sciamus.contractanalyzer.checks.dummy;

import com.sciamus.contractanalyzer.checks.RestContractCheck;
import com.sciamus.contractanalyzer.reporting.ReportResults;
import com.sciamus.contractanalyzer.reporting.TestReport;
import com.sciamus.contractanalyzer.reporting.TestReportBuilder;
import org.springframework.stereotype.Component;

import java.net.URL;

@Component
public class DummyRestContractCheck implements RestContractCheck {


    private final static String NAME = "Dummy Check";


//    public TestReport runAsAutogenerated (URL url) {
//
//        TestReport testReport = this.run(url);
//
//        return testReport.addAutogenerated();
//    }


    public TestReport run(URL Url) {

        return new TestReportBuilder()
                .setNameOfCheck(this.getName())
                .setReportBody("Run on "+Url)
                .setResult(ReportResults.PASSED)
                .createTimestamp()
                .createTestReport();

//        return new TestReport(ReportResults.PASSED,
//                this.getName()+ " is always PASSED" + " Run on:" + Url,
//                this.getName());
    }

    @Override
    public String getName() {
        return NAME;
    }


}
